// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc_message.proto

package com.pactera.rb.proto;

public interface RbCallBackOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Robot.RbCallBack)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *函数名
   * </pre>
   *
   * <code>string func = 1;</code>
   */
  java.lang.String getFunc();
  /**
   * <pre>
   *函数名
   * </pre>
   *
   * <code>string func = 1;</code>
   */
  com.google.protobuf.ByteString
      getFuncBytes();

  /**
   * <pre>
   *参数Map,k=paramName,v=paramValue
   * </pre>
   *
   * <code>map&lt;string, string&gt; params = 2;</code>
   */
  int getParamsCount();
  /**
   * <pre>
   *参数Map,k=paramName,v=paramValue
   * </pre>
   *
   * <code>map&lt;string, string&gt; params = 2;</code>
   */
  boolean containsParams(
      java.lang.String key);
  /**
   * Use {@link #getParamsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getParams();
  /**
   * <pre>
   *参数Map,k=paramName,v=paramValue
   * </pre>
   *
   * <code>map&lt;string, string&gt; params = 2;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getParamsMap();
  /**
   * <pre>
   *参数Map,k=paramName,v=paramValue
   * </pre>
   *
   * <code>map&lt;string, string&gt; params = 2;</code>
   */

  java.lang.String getParamsOrDefault(
      java.lang.String key,
      java.lang.String defaultValue);
  /**
   * <pre>
   *参数Map,k=paramName,v=paramValue
   * </pre>
   *
   * <code>map&lt;string, string&gt; params = 2;</code>
   */

  java.lang.String getParamsOrThrow(
      java.lang.String key);
}
