// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc_message.proto

package com.pactera.rb.proto;

public interface RbRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Robot.RbRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userId = 1;</code>
   */
  java.lang.String getUserId();
  /**
   * <code>string userId = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>string query = 2;</code>
   */
  java.lang.String getQuery();
  /**
   * <code>string query = 2;</code>
   */
  com.google.protobuf.ByteString
      getQueryBytes();
}
