// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpc_message.proto

package com.pactera.rb.proto;

public interface RbResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Robot.RbResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 成员变量都有一个唯一的数字标志(Assigning Tags like =1,2,3)
   * </pre>
   *
   * <code>string key = 1;</code>
   */
  java.lang.String getKey();
  /**
   * <pre>
   * 成员变量都有一个唯一的数字标志(Assigning Tags like =1,2,3)
   * </pre>
   *
   * <code>string key = 1;</code>
   */
  com.google.protobuf.ByteString
      getKeyBytes();

  /**
   * <code>string tts = 2;</code>
   */
  java.lang.String getTts();
  /**
   * <code>string tts = 2;</code>
   */
  com.google.protobuf.ByteString
      getTtsBytes();

  /**
   * <code>string screenShow = 3;</code>
   */
  java.lang.String getScreenShow();
  /**
   * <code>string screenShow = 3;</code>
   */
  com.google.protobuf.ByteString
      getScreenShowBytes();

  /**
   * <code>repeated string recommendList = 4;</code>
   */
  java.util.List<java.lang.String>
      getRecommendListList();
  /**
   * <code>repeated string recommendList = 4;</code>
   */
  int getRecommendListCount();
  /**
   * <code>repeated string recommendList = 4;</code>
   */
  java.lang.String getRecommendList(int index);
  /**
   * <code>repeated string recommendList = 4;</code>
   */
  com.google.protobuf.ByteString
      getRecommendListBytes(int index);

  /**
   * <code>string responseType = 5;</code>
   */
  java.lang.String getResponseType();
  /**
   * <code>string responseType = 5;</code>
   */
  com.google.protobuf.ByteString
      getResponseTypeBytes();

  /**
   * <code>string recommendVagueMsg = 6;</code>
   */
  java.lang.String getRecommendVagueMsg();
  /**
   * <code>string recommendVagueMsg = 6;</code>
   */
  com.google.protobuf.ByteString
      getRecommendVagueMsgBytes();

  /**
   * <pre>
   *等同 List&lt;RbCallBack&gt;, k函数名，v参数 json封装
   * </pre>
   *
   * <code>repeated .Robot.RbCallBack events = 7;</code>
   */
  java.util.List<com.pactera.rb.proto.RbCallBack> 
      getEventsList();
  /**
   * <pre>
   *等同 List&lt;RbCallBack&gt;, k函数名，v参数 json封装
   * </pre>
   *
   * <code>repeated .Robot.RbCallBack events = 7;</code>
   */
  com.pactera.rb.proto.RbCallBack getEvents(int index);
  /**
   * <pre>
   *等同 List&lt;RbCallBack&gt;, k函数名，v参数 json封装
   * </pre>
   *
   * <code>repeated .Robot.RbCallBack events = 7;</code>
   */
  int getEventsCount();
  /**
   * <pre>
   *等同 List&lt;RbCallBack&gt;, k函数名，v参数 json封装
   * </pre>
   *
   * <code>repeated .Robot.RbCallBack events = 7;</code>
   */
  java.util.List<? extends com.pactera.rb.proto.RbCallBackOrBuilder> 
      getEventsOrBuilderList();
  /**
   * <pre>
   *等同 List&lt;RbCallBack&gt;, k函数名，v参数 json封装
   * </pre>
   *
   * <code>repeated .Robot.RbCallBack events = 7;</code>
   */
  com.pactera.rb.proto.RbCallBackOrBuilder getEventsOrBuilder(
      int index);

  /**
   * <pre>
   *等同 List&lt;RbCallBack&gt;, k函数名，v参数 json封装
   * </pre>
   *
   * <code>repeated .Robot.RbCallBack actions = 8;</code>
   */
  java.util.List<com.pactera.rb.proto.RbCallBack> 
      getActionsList();
  /**
   * <pre>
   *等同 List&lt;RbCallBack&gt;, k函数名，v参数 json封装
   * </pre>
   *
   * <code>repeated .Robot.RbCallBack actions = 8;</code>
   */
  com.pactera.rb.proto.RbCallBack getActions(int index);
  /**
   * <pre>
   *等同 List&lt;RbCallBack&gt;, k函数名，v参数 json封装
   * </pre>
   *
   * <code>repeated .Robot.RbCallBack actions = 8;</code>
   */
  int getActionsCount();
  /**
   * <pre>
   *等同 List&lt;RbCallBack&gt;, k函数名，v参数 json封装
   * </pre>
   *
   * <code>repeated .Robot.RbCallBack actions = 8;</code>
   */
  java.util.List<? extends com.pactera.rb.proto.RbCallBackOrBuilder> 
      getActionsOrBuilderList();
  /**
   * <pre>
   *等同 List&lt;RbCallBack&gt;, k函数名，v参数 json封装
   * </pre>
   *
   * <code>repeated .Robot.RbCallBack actions = 8;</code>
   */
  com.pactera.rb.proto.RbCallBackOrBuilder getActionsOrBuilder(
      int index);

  /**
   * <pre>
   *新增字段,节点搜索路径
   * </pre>
   *
   * <code>string path = 9;</code>
   */
  java.lang.String getPath();
  /**
   * <pre>
   *新增字段,节点搜索路径
   * </pre>
   *
   * <code>string path = 9;</code>
   */
  com.google.protobuf.ByteString
      getPathBytes();

  /**
   * <pre>
   *&#47;/新增字段,上下文
   * </pre>
   *
   * <code>string context = 10;</code>
   */
  java.lang.String getContext();
  /**
   * <pre>
   *&#47;/新增字段,上下文
   * </pre>
   *
   * <code>string context = 10;</code>
   */
  com.google.protobuf.ByteString
      getContextBytes();
}
